# Main config for SkyblockD plugin
# Made with <3 by Maxus
# https://github.com/Maxuss | https://maxus.space

skyblockd:
  chat:
    shout:
      enabled: true
      hasCooldown: true
      cooldown: 10
    ranks:
      enabled: true
      interceptMessages: true
  commands:
    devmode: true
  motd:
    enabled: true
    extraMessages:
      - $cHello, i am a cool message in red!
      - $6Hello, i am a cool message with\nan escape sequence!
